### PR TITLE
Adding Windows version of script to run tests

### PR DESCRIPTION
**Pull request by dmendelowitz**
There is now a Powershell script that has the same functionality as the bash script for running tests but will work on Windows operating systems. The script is basically a 1:1 translation of `run_tests.sh` but in Powershell, so when testing, make sure that the new script works how you would expect the other version of the script to work.

You should be able to run the script by calling `./testing-harness/scripts/run_tests.ps1` from a Powershell command line or `powershell.exe ./testing-harness/scripts/run_tests.ps1` from a non-Powershell command line. The output should look the same as the normal output of running `run_tests.sh`.

### CODE REVIEW

**Comment by dmendelowitz** [comment]
.bat file version is now ready to be tested. Nothing new to add other than that batch is kind of funky looking so let me know if you have questions and you should be able to test the script via the new run.js entrypoint.

**Comment by Dtphelan1** [comment]
Giving this another review now. In the meantime, it looks like this PR would benefit from a rebase.

**Comment by Dtphelan1** [comment]
Great news: The BAT file works as expected with minimal troubleshooting! Huge props to you @dmendelowitz for translating a shell script into two different Windows scripting languages in one task. That's a massive feat. 

Troubleshooting knowledge: The STEAM VM is _very unhappy_ with newer versions of docker. I needed to rollback to Docker CE 17.12.0-ce-win46, from Jan of 2018. 😨 

Minor comments:
- I keep getting messages to the console that the timeout command is incorrectly being called. This causes the wait-till-container-is-up routine to fail. Photo of the error message below.
- It looks like we don't `docker stop` our docker instance after finishing our script, which we do in the `.sh` version. Could we add that? 
- It looks like we don't check to see if a docker container is already running, as we do in the `.sh` version. Do we want to add that, or was duplicating that a headache? 

image

**Comment by dmendelowitz** [comment]
> Great news: The BAT file works as expected with minimal troubleshooting! Huge props to you @dmendelowitz for translating a shell script into two different Windows scripting languages in one task. That's a massive feat.
> 
> Troubleshooting knowledge: The STEAM VM is _very unhappy_ with newer versions of docker. I needed to rollback to Docker CE 17.12.0-ce-win46, from Jan of 2018. 😨
> 
> Minor comments:
> 
> * I keep getting messages to the console that the timeout command is incorrectly being called. This causes the wait-till-container-is-up routine to fail. Photo of the error message below.
> * It looks like we don't check to see if a docker container is already running, as we do in the `.sh` version. Do we want to add that, or was duplicating that a headache?
> 
> image

So based on your screen shot, are you running the script in MinGW? If so, you aren't actually running it on windows, right? For example I get that same error about timeout when I run a timeout command in WSL instead of actual windows command line.

In regards to stopping existing docker containers, that happens on line 24

I will check to see what version of docker I have and see how that compares to what you had to downgrade to.

**Comment by dmendelowitz** [comment]
The script runs for me on docker version 20.10.5

**Comment by Dtphelan1** [comment]
The comment about docker versions is VM-specific. I'm not surprised you're able to run more modern versions. Consider that remark as situational awareness, not feedback.

**Comment by Dtphelan1** [comment]
Running the tool with Windows Command Prompt now and will report how that goes

**Comment by Dtphelan1** [comment]
The warning I was seeing about timeout arguments being malformed is gone now that I'm running things in Command Prompt. However, it does appear that the actual Waiting subroutine isn't working. When I run it the first time, I get an error due to the container not being up yet; when I run translate after manually pausing a few beats, translation occurs successfully now that the container is up.
image
image

**Comment by Dtphelan1** [comment]
Stopping of previous containers works when run on Command Prompt

**Comment by dmendelowitz** [comment]
> The warning I was seeing about timeout arguments being malformed is gone now that I'm running things in Command Prompt. However, it does appear that the actual Waiting subroutine isn't working. When I run it the first time, I get an error due to the container not being up yet; when I run translate after manually pausing a few beats, translation occurs successfully now that the container is up.
> image
> image

This was related to the use of errorlevel, I think it should be fixed now

**Comment by Dtphelan1** [comment]
New script works perfectly well, though the VM is still terribly fragile w/r/t Docker. Great work Dylan, that addresses all my comments :smil

**Review by Dtphelan1 — APPROVED** [review]

**Comment by dmendelowitz** [comment]
I noticed while reviewing @mgramigna's PR for the new testing harness repo https://github.com/mcode/cql-testing-harness/pull/1 that this script probably needs to end up over there eventually and there have been some changes to the .sh version that I probably want to replicate in this script. So I'm unsure if we still want to merge this here or wait until the separation PRs are approved and start a new PR with this script and some new changes over on the cql-testing-harness repo

**Comment by mgramigna** [comment]
@dmendelowitz I was anticipating this. My gut feeling was to just merge the windows script here as is so it works and then we can port over any necessary changes on the testing harness PR itself after this is merged.

**Review by jafeltra — APPROVED** [review]
Looks great!

**Pull request merged**
