### PR TITLE
Refactor to use separate testing harness

### PR DESCRIPTION
**Pull request by mgramigna**
**Note**: Do not merge until GH actions issue is resolved and cql-testing-harness is published to NPM

See https://github.com/mcode/cql-testing-harness/pull/1 for the code that was moved to a separate library.

This PR simplifies the code used in mcode-cql to rely on the testing harness as an external dependency. The functionality should be exactly the same as it was before, except there are no scripts to translate/test the testing harness itself, as those now live in a separate repository.

There are currently issues in CI with installing the cql-testing-harness via yarn with https instead of an npm registry. For now, my plan is to just publish the cql-testing-harness to npm after the above PR gets merged. Then I will update this one and it should pass CI. This is still testable though.

**Open Question**: Are people ok if I trim down the docs of the README in this repo now? I included testing-harness specific details in the README on that repo, so I think this README can be simplified to show how to use the testing harness rather than describe all of the inner workings.

### CODE REVIEW

**Comment by jafeltra** [comment]
This makes sense to me! I tried linking the `cql-testing-harness` library locally and everything worked as expected.

I personally am in favor of trimming down the README here to only include information about how to write CQL and tests for it while using the `cql-testing-harness`.

**Review by dmendelowitz — APPROVED** [review]
This looks good to me. I think it makes sense to trim down the README here as long as you point users to the README of the new testing harness

**Comment by mgramigna** [comment]
Sounds good. I'll update the README, and then we can hold off merging until the other PR is merged and I update the dependency of this branch

**Comment by mgramigna** [comment]
This should be ready to go now with CI passing pending no further comments

**Review by jafeltra — APPROVED** [review]
Looks good!

**Comment by jafeltra** [comment]
Actually I have one more question. I don't know how git will work on this one, but will the `run_tests.bat` file get removed if you removed it's parent directory? Or does this need to be rebased and then remove the file?

**Review by jafeltra — COMMENTED** [review]
Actually I have one more question. I don't know how git will work on this one, but will the run_tests.bat file get removed if you removed its parent directory? Or does this need to be rebased and then remove the file?

**Comment by mgramigna** [comment]
@jafeltra good catch. The .bat file will persist. I'm going to rebase and remove it if that's cool

**Review by jafeltra — APPROVED** [review]
Looks good! No `.bat` file and latest cql-testing-harness!

**Pull request merged**
