### PR TITLE
Configurable translation url

### PR DESCRIPTION
**Pull request by julianxcarter**
Allows for users to set a custom URL for the CQL translation service by way of setting a node environment variable. This is done by requiring users to create a `.env` file to set the environment variable to their preferred URL, and then using the `dotenv` package to read in the environment variable from the file. A default url of `http://localhost:8080/cql/translator` is used when the custom URL is not found.

To test, just create a `.env` file within the base directory of mcode-cql and add this line to the file:
```
TRANSLATION_SERVICE_URL=http://preferredURL.com
```
If you console.log the `TRANSLATION_SERVICE_URL` variable within the `build.js` file, it should be whatever you set the variable to within your `.env` file.

### CODE REVIEW

**Review by mgramigna — CHANGES_REQUESTED** [review]
Nice. I like the .env approach.

It might be worth mentioning in the README that another option is to not just create the file, but rather you can provide the argument at runtime as well. dotenv should play nicely with this. I.e., both of these are valid:

1) create a `.env` file within the base diretory of `mcode-cql` and enter a custom URL like so:
``` bash
TRANSLATION_SERVICE_URL=http://secondUrl.com
``` 

2) Provide the URL at runtime of the command:

``` bash
TRANSLATION_SERVICE_URL=http://preferredURL.com yarn test -n
```

Should also work provided the user has a server running at the specified URL (the `-n` flag tells the script to not start a docker container)

**Comment by julianxcarter** [comment]
Readme has been updated in `e39fc41` @mgramigna.

**Comment by mgramigna** [comment]
Ah crap, I guess since the README portion is in the translation section, we should probably use `yarn translate` as our example command there instead of `yarn test` (in which case the -n isn't needed).

That's my bad, sorry

**Comment by julianxcarter** [comment]
I just switched the example command to the `yarn translate` command. I thought the blurb about using the `-n` flag on yarn test was useful though so I left that!

**Comment by Dtphelan1** [comment]
One small thing: it might be nice to have a `.env.example` file in the base repository, similar to how we have our config.example.json file in the MEF. That file could include the default values you describe in the README, and the README instructions can be to rename that file and update those values accordingly. Thoughts on this approach @julianxcarter?

**Comment by julianxcarter** [comment]
> One small thing: it might be nice to have a `.env.example` file in the base repository, similar to how we have our config.example.json file in the MEF. That file could include the default values you describe in the README, and the README instructions can be to rename that file and update those values accordingly.

I really like this idea! I'll get to work on adding this now

**Review by mgramigna — APPROVED** [review]

**Review by Dtphelan1 — APPROVED** [review]

**Pull request merged**
